### ISSUE TITLE
weird crash in softcam startup after choosing emu

### ISSUE THREAD

**Issue by ahmedmoselhi** [teamblue-e2/enigma2#35]
**Describe the bug**
after i select a cam in softcamsetup screen and press green button this error appears : 
`2022-03-30 22:04:34+0200 [-] Traceback (most recent call last):
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 60, in action
2022-03-30 22:04:34+0200 [-]     res = self.actions[action]()
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftcamStartup/SoftcamStartup.py", line 142, in save
2022-03-30 22:04:34+0200 [-]     self.restart(what)
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftcamStartup/SoftcamStartup.py", line 99, in restart
2022-03-30 22:04:34+0200 [-]     self.mbox = self.session.open(MessageBox, msg, MessageBox.TYPE_INFO)
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/StartEnigma.py", line 346, in open
2022-03-30 22:04:34+0200 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/StartEnigma.py", line 289, in instantiateDialog
2022-03-30 22:04:34+0200 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/StartEnigma.py", line 313, in doInstantiateDialog
2022-03-30 22:04:34+0200 [-]     dlg.applySkin()
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 246, in applySkin
2022-03-30 22:04:34+0200 [-]     self.createGUIScreen(self.instance, self.desktop)
2022-03-30 22:04:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 274, in createGUIScreen
2022-03-30 22:04:34+0200 [-]     exec(f, globals(), locals())
2022-03-30 22:04:34+0200 [-]   File "skin applet", line 23, in <module>
2022-03-30 22:04:34+0200 [-] AttributeError: 'MenuList' object has no attribute 'count'
`
**To Reproduce**
1. Go to 'go to setup > cam/ci > softcam startup'
2. Select cam and Press green button
3. See error

**Expected behavior**
should see softcam start message

**Comment by ahmedmoselhi** [comment]
btw i use python3 branch in my build (:
