### ISSUE TITLE
InfoBarGenerics.py in 7.3

### ISSUE THREAD

**Issue by islamsabry2008** [teamblue-e2/enigma2#46]
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_update
2024-01-13 07:57:25+0200 [-] Traceback (most recent call last):
2024-01-13 07:57:25+0200 [-]   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 411, in doDimming
2024-01-13 07:57:25+0200 [-]   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 503, in doHide
2024-01-13 07:57:25+0200 [-]   File "/usr/lib/enigma2/python/Components/config.py", line 1972, in __getattr__
2024-01-13 07:57:25+0200 [-] AttributeError: osd_alpha
[ePyObject] (CallObject(<bound method InfoBarShowHide.doDimming of <class 'Screens.InfoBar.InfoBar'>>,()) failed)

**Comment by teamblue-e2** [comment]
What did you do to produce that error.
changing transparency is working for me.

**Comment by islamsabry2008** [comment]
I did not do any thing I compile for zgemma h9twin( Which I know you do not support) so there is 2 errors
1- in [skin_display_7segment.xml] so I added it to my fork
2- this appears later after installing
